DROP DATABASE IF EXISTS staffDB;
CREATE DATABASE staffDB;

USE staffDB;

DROP TABLE IF EXISTS department;
CREATE TABLE department(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30) NOT NULL
);

DROP TABLE IF EXISTS role;
CREATE TABLE role(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(30) NOT NULL,
salary DEC(8,2) NOT NULL,
department_id INT NOT NULL,
);

DROP TABLE IF EXISTS employees;

CREATE TABLE employees(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
role_id INT NOT NULL,
manager_id INT NULL
)
